baseurl="http://chrismeserole.com/"
copyright = "&copy; 2004-2017"
disqusshortname = ""
languagecode = "en-us"
paginate = 5
pluralizelisttitles = false
theme = "isola"
title = "Chris Meserole"

[[menu.main]]
identifier = "blog"
name = "Blog"
url = "/blog/"
weight = -120

[[menu.main]]
name = "Twitter"
url = "https://twitter.com/chrismeserole"
weight = 120

[[menu.main]]
name = "Github"
url = "https://github.com/chrismeserole"
weight = 130

[params]
author = "Chris Meserole"
authorlocation = "Washington, D.C."
authorwebsite = "http://chrismeserole.com"
bio = "Religion, Peace, Conflict, and Data Science."
#cover = "images/amman.jpg"

#description = "writer and researcher"
twitterDescription = "Personal website of Chris Meserole"
githubName = "chrismeserole"
googleAnalyticsUserID = "UA-61270828-2"
hideHUGOSupport = false
logo = "images/cm-logo-300dpi.png"
twitterName = "chrismeserole"

[permalinks]
	blog = "blog/:slug/:year/"
	signals = "signals/:slug/"
	coding = "coding/:slug/"

[sitemap]
	ChangeFreq = ""
	Filename = "sitemap.xml"
	Priority = "-1"
